import type { NextPage } from 'next'
import Head from 'next/head'
import InputField from '../components/InputField'


const Home: NextPage = () => {
  return (
    <div className='container'>
      <Head>
        <title>Task List App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className='heading'>Task List App</h1>
      <InputField/>
    </div>
  )
}
export default Home
